#!/bin/bash

# rose pine colors
love=#eb6f92
gold=#f6c177
rose=#ebbcba
pine=#31748f
foam=#9ccfd8
iris=#c4a7e7
overlay=#26233a
bg=#25233a
subtle=#908caa
fg=#e0def4

interval=0

wlan() {
  interface='wlp3s0'
  ssid=$(iw $interface link | grep 'SSID' | awk 'NR%1==0 {print $2}')

  case "$(cat /sys/class/net/wl*/operstate 2>/dev/null)" in
    up) printf "^c$rose^󰤨 $ssid^d^" ;;
    down) printf "^c$subtle^󰤮 offline^d^" ;;
  esac
}

vol() {
  [ $(pamixer --get-mute) = true ] && echo " Ø" && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon=" "
elif [ "$vol" -lt "30" ]; then
	icon=" "
else
	icon=" "
fi

printf "^c#a3be8c^$icon$vol"
}

ram() {
  mem_total=$(free -m | awk 'NR%2==0 {print $2}')
  mem_avail=$(free -m | awk 'NR%2==0 {print $7}')
  mem_used=$(( $mem_total - $mem_avail ))
  mem_usage=$(( $mem_used * 100 / $mem_total ))
  if [ $mem_usage -ge 80 ]; then
    printf "^c$love^󰘚 ${mem_usage}%%!"
  else
    printf "^c$pine^󰘚 ${mem_usage}%%"
  fi
}

backlight() {
	icon=" "
	backlight=$(printf "%.0f\n" `light -G`)
	printf "^c#a3be8c^$icon$backlight"
}

temp_cpu() {
  crit=50

  read -r temp </sys/class/thermal/thermal_zone0/temp
  temp="${temp%???}"

  if [ "$temp" -lt "$crit" ] ; then
      printf "^c#a3be8c^ $temp°"
  else
      printf "^c#a3be8c^ $temp°"
  fi
}

BT() {
# Get the Bluetooth status
    BT_STATUS=$(bluetoothctl show | grep "Powered:" | awk '{print $2}')

    echo "$(date): Bluetooth status: $BT_STATUS" >> $LOGFILE

    # Determine the display message
    if [ "$BT_STATUS" = "yes" ]; then
        # Get connected devices
        BT_DEVICES=$(bluetoothctl devices Connected | awk -F' ' '{print $3, $4, $5}')
        
        if [ -z "$BT_DEVICES" ]; then
            BT_MESSAGE="On (No connected devices)"
        else
            BT_MESSAGE="On ($BT_DEVICES)"
        fi
    else
        BT_MESSAGE="Off"
    fi
}

while true; do
  interval=$((interval + 1))
  xsetroot -name  " $(BT) $(temp_cpu) $(backlight) $(vol) $(ram) $(wlan) $(date +"^c$iris^󰃮 %a %d %B 󱑇 %I:%M %p")   "
  sleep 1
done
