#!/bin/bash

function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

light -S 20 &

#nm-applet &

pgrep -x picom > /dev/null || picom --config $HOME/.config/bspwm/picom.conf &

xsetroot -cursor_name left_ptr &

feh --no-fehbg --bg-fill $HOME/.config/bspwm/great-wave-of-kanagawa-gruvbox.png &

pgrep -x dunst > /dev/null || dunst -config $HOME/.config/dunst/dunstrc &

/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

run xfce4-power-manager &

picom --config $HOME/.config/picom/picom.conf &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

numlockx off &




