#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

light -S 20 &

#nm-applet &

pgrep -x picom > /dev/null || picom --config $HOME/.config/bspwm/picom.conf &

xsetroot -cursor_name left_ptr &

feh --no-fehbg --bg-fill $HOME/.config/bspwm/great-wave-of-kanagawa-gruvbox.png &

pgrep -x dunst > /dev/null || dunst -config $HOME/.config/dunst/dunstrc &

/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# Enable power management
xfce4-power-manager &




