#! /bin/sh

#
# Startup Applications
#
$HOME/.config/bspwm/autostart

export PATH="$HOME/.config/scripts:$PATH"

#
# define colorscheme
#
focus="#ebdbb2"
normal="#282828"

#
# Workspace
#
bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

#
# Window Configurations
#
bspc config border_width   2
bspc config border_radius  5
bspc config window_gap     15
bspc config top_padding    23
bspc config bottom_padding 0
bspc config right_padding  0
bspc config left_padding   0

#
# User Interface
#
bspc config split_ratio               0.50
bspc config borderless_monocle        false
bspc config gapless_monocle           false
bspc config focus_follows_pointer     false
bspc config pointer_follows_focus     false
bspc config pointer_follows_monitor   true
bspc config ignore_ewmh_fullscreen    none
bspc config ignore_ewmh_focus         false
bspc config remove_unplugged_monitors true
bspc config normal_border_color       $normal
bspc config active_border_color       $focus
bspc config focused_border_color      $focus

###METAMASK####
bspc rule -a Google-chrome:crx_nkbihfbeogaeaoehlefnkodbefgpgknn state=floating
###HIRO WALLET###
bspc rule -a Google-chrome:crx_ldinpeekobnhjjdofggfgjlcehhmanlj state=floating
###SUI WALLET###
bspc rule -a Google-chrome:crx_opcgpfmipidbgpenhmajoajpbobppdil state=floating
###Rabby WALLET###
bspc rule -a Google-chrome:crx_acmacodkjbdgmoleebolmdjonilkdbch state=floating
###VENOM WALLET###
bspc rule -a Google-chrome:crx_ojggmchlghnjlapmfbnjholfjkiidbch state=floating
###Manta Wallet###
bspc rule -a Google-chrome:crx_enabgbdfcbaehmbigakijjabdpdnimlg state=floating
###Fuelet Wallet###
bspc rule -a Google-chrome:crx_bifidjkcdpgfnlbcjpdkdcnbiooooblg state=floating


#bspc rule -a Google-chrome:google-chrome state=floating
bspc rule -a Google-chrome:task_dialog state=floating
bspc rule -a feh state=fullscreen
bspc rule -a st-256color state=floating
# Floating rule for Kitty terminal
#bspc rule -a kitty:kitty state=floating rectangle=800x600

declare -a floating=(alacritty-float Pcmanfm Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor calamares Calamares)

for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on
done


