#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Script to manage speaker volume on Archcraft.

# Icons
iDIR='/usr/share/archcraft/icons/dunst'
notify_cmd='dunstify -u low -h string:x-dunst-stack-tag:obvolume'

# Get Volume
get_volume() {
	echo "$(pamixer --get-volume)"
}

# Get icons
get_icon() {
	current="$(get_volume)"
	if [[ "$current" -eq "0" ]]; then
		icon="$iDIR/volume-mute.png"
	elif [[ "$current" -le "30" ]]; then
		icon="$iDIR/volume-low.png"
	elif [[ "$current" -le "60" ]]; then
		icon="$iDIR/volume-mid.png"
	elif [[ "$current" -le "100" ]]; then
		icon="$iDIR/volume-high.png"
	fi
}

# Notify
notify_user() {
	${notify_cmd} -i "$icon" "Volume : $(get_volume)%"
}

# Increase Volume
inc_volume() {
	[[ "$(pamixer --get-mute)" == "true" ]] && pamixer --unmute
	pamixer --increase 5 && get_icon && notify_user
}

# Decrease Volume
dec_volume() {
	[[ "$(pamixer --get-mute)" == "true" ]] && pamixer --unmute
	pamixer --decrease 5 && get_icon && notify_user
}

# Toggle Mute
toggle_mute() {
	if [[ "$(pamixer --get-mute)" == "false" ]]; then
		pamixer --toggle-mute && ${notify_cmd} -i "$iDIR/volume-mute.png" "Mute"
	else
		pamixer --toggle-mute && get_icon && ${notify_cmd} -i "$icon" "Unmute"
	fi
}

# Toggle Mic
toggle_mic() {
	ID="$(pamixer --list-sources | grep 'Default' | cut -d',' -f1 | cut -d' ' -f3)"
	if [[ "$(pamixer --source $ID --get-mute)" == "false" ]]; then
		pamixer --source ${ID} --toggle-mute && ${notify_cmd} -i "$iDIR/microphone-mute.png" "Microphone Switched OFF"
	else
		pamixer --source ${ID} --toggle-mute && ${notify_cmd} -i "$iDIR/microphone.png" "Microphone Switched ON"
	fi
}

# Execute accordingly
if [[ -x "$(which pamixer)" ]]; then
	if [[ "$1" == "--get" ]]; then
		get_volume
	elif [[ "$1" == "--inc" ]]; then
		inc_volume
	elif [[ "$1" == "--dec" ]]; then
		dec_volume
	elif [[ "$1" == "--toggle" ]]; then
		toggle_mute
	elif [[ "$1" == "--toggle-mic" ]]; then
		toggle_mic
	else
		echo $(get_volume)%
	fi
else
	${notify_cmd} "'pamixer' is not installed."
fi
